name: Module Import Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Test module imports correctly
        shell: pwsh
        run: |
          Import-Module .\Demo.psd1
